"""
reporter.py — Comprehensive Forensic Report Generator.
Exports triage verdicts into Markdown, standalone HTML, JSON, and STIX 2.1 formats.
Adheres strictly to zero-emoji, clean ASCII badges, and empirical proof presentation.
"""

import json
import uuid
import datetime
from pathlib import Path
from typing import Dict, Any, Optional
from .models import TriageAnalysisResult
from .export_engine import ExportEngine


class ReportGenerator:
    """Generates structured Markdown, HTML, JSON, and STIX 2.1 DFIR triage reports."""

    def __init__(self, result: TriageAnalysisResult):
        self.result = result

    def generate_json(self, output_path: str) -> str:
        """Exports raw deterministic triage result to structured JSON for SIEM/SOAR integration."""
        data = {
            "threat_score": self.result.threat_score,
            "risk_level": self.result.risk_level,
            "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "mitre_techniques": self.result.mitre_techniques,
            "findings_count": len(self.result.findings),
            "findings": [
                {
                    "severity": f.severity,
                    "category": f.category,
                    "title": f.title,
                    "description": f.description,
                    "evidence_proof": f.evidence_proof,
                    "pid": f.pid,
                    "memory_offset": f.memory_offset,
                    "correlated_findings": f.correlated_findings,
                }
                for f in self.result.findings
            ],
            "remediation_steps": self.result.remediation_steps,
            "ai_summary": self.result.ai_summary,
        }
        content = json.dumps(data, indent=2)
        Path(output_path).write_text(content, encoding="utf-8")
        return content

    def generate_stix(self, output_path: str) -> str:
        """Exports triage indicators to STIX 2.1 JSON format for Threat Intel sharing."""
        findings_dict_list = [
            {
                "id": f.pid or f.memory_offset or f.title,
                "name": f.title,
                "severity": f.severity,
                "category": f.category,
                "description": f.description,
                "findings": f.evidence_proof,
            }
            for f in self.result.findings
        ]
        stix_bundle = ExportEngine.to_stix2(findings_dict_list, bundle_name="vol3-triage-indicators")
        content = json.dumps(stix_bundle, indent=2)
        Path(output_path).write_text(content, encoding="utf-8")
        return content

    def generate_markdown(self, output_path: str) -> str:
        """Generates a GitHub-flavored Markdown report with Evidence Proofing and Zero-Emoji."""
        findings_table = "| Severity | Category | Title | Evidence Proof |\n|---|---|---|---|\n"
        if not self.result.findings:
            findings_table += "| [ NONE ] | Clean | No Anomalies Detected | Memory dump showed no high-confidence injection or anomaly signatures. |\n"
        else:
            for f in self.result.findings:
                proof_clean = f.evidence_proof.replace("\n", " ") if f.evidence_proof else f.description.replace("\n", " ")
                findings_table += f"| **[ {f.severity} ]** | {f.category} | {f.title} | `{proof_clean}` |\n"

        mitre_list = "\n".join([f"- `{t}`" for t in self.result.mitre_techniques]) if self.result.mitre_techniques else "- [ NONE ] No direct MITRE ATT&CK techniques mapped."
        remediations_list = "\n".join([f"1. {r}" for r in self.result.remediation_steps]) if self.result.remediation_steps else "1. No immediate remediation actions required."

        content = f"""# [ DFIR ] Memory Forensics & Incident Triage Report

**Threat Score**: `{self.result.threat_score}/100` | **Risk Level**: `[ {self.result.risk_level} ]`

---

## [ 1. EXECUTIVE SUMMARY ]

{self.result.ai_summary}

---

## [ 2. CORRELATED ANOMALY FINDINGS ({len(self.result.findings)}) ]

{findings_table}

---

## [ 3. MITRE ATT&CK MATRIX MAPPING ]

{mitre_list}

---

## [ 4. RECOMMENDED DFIR REMEDIATION ROADMAP ]

{remediations_list}

---
*Generated by Volatility 3 Cyber Suite v2.0.0 — Zero-Dependency DFIR Architecture.*
"""
        Path(output_path).write_text(content, encoding="utf-8")
        return content

    def generate_html(self, output_path: str) -> str:
        """Generates a self-contained HTML forensic dashboard report without external CDN scripts."""
        findings_rows = ""
        for f in self.result.findings:
            badge_class = f"badge-{f.severity.lower()}"
            proof = f.evidence_proof.replace("<", "&lt;").replace(">", "&gt;") if f.evidence_proof else "N/A"
            findings_rows += f"""
            <tr>
                <td><span class="badge {badge_class}">[ {f.severity} ]</span></td>
                <td><strong>{f.category}</strong></td>
                <td>{f.title}</td>
                <td><code>{proof}</code></td>
            </tr>
            """

        if not findings_rows:
            findings_rows = "<tr><td colspan='4' style='text-align:center;'>[ CLEAN ] No anomalies detected in analyzed memory space.</td></tr>"

        mitre_badges = "".join([f"<span class='mitre-badge'>{t}</span>" for t in self.result.mitre_techniques])
        remediations_html = "".join([f"<li>{r}</li>" for r in self.result.remediation_steps])

        score_color = "#ef4444" if self.result.threat_score >= 75 else "#f59e0b" if self.result.threat_score >= 50 else "#10b981"

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DFIR Triage Report — Volatility 3 Cyber Suite</title>
    <style>
        :root {{
            --bg: #090a0f;
            --surface: #12141c;
            --border: #232738;
            --text-main: #f4f4f5;
            --text-muted: #94a3b8;
            --accent: #38bdf8;
            --critical: #ef4444;
            --high: #f97316;
            --medium: #f59e0b;
            --low: #10b981;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: var(--bg);
            color: var(--text-main);
            margin: 0;
            padding: 2rem;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        header {{
            border-bottom: 1px solid var(--border);
            padding-bottom: 1.5rem;
            margin-bottom: 2rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 1rem;
        }}
        h1, h2, h3 {{ margin: 0 0 0.5rem 0; font-weight: 700; }}
        .header-title {{ font-size: 1.5rem; }}
        .score-box {{
            background: var(--surface);
            border: 1px solid var(--border);
            padding: 1rem 1.5rem;
            border-radius: 8px;
            text-align: right;
        }}
        .score-val {{ font-size: 2rem; font-weight: 800; color: {score_color}; }}
        .card {{
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 2rem;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 1rem;
            font-size: 0.9rem;
        }}
        th, td {{
            padding: 0.75rem 1rem;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }}
        th {{ background: #181b26; color: var(--text-muted); font-size: 0.8rem; text-transform: uppercase; }}
        code {{
            background: #0f172a;
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-family: monospace;
            color: var(--accent);
            font-size: 0.85rem;
            word-break: break-all;
        }}
        .badge {{
            padding: 0.25rem 0.6rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 700;
            display: inline-block;
        }}
        .badge-critical {{ background: rgba(239,68,68,0.2); color: var(--critical); border: 1px solid var(--critical); }}
        .badge-high {{ background: rgba(249,115,22,0.2); color: var(--high); border: 1px solid var(--high); }}
        .badge-medium {{ background: rgba(245,158,11,0.2); color: var(--medium); border: 1px solid var(--medium); }}
        .badge-low {{ background: rgba(16,185,129,0.2); color: var(--low); border: 1px solid var(--low); }}
        .mitre-badge {{
            background: #1e293b;
            color: #38bdf8;
            border: 1px solid #334155;
            padding: 0.3rem 0.6rem;
            border-radius: 4px;
            font-size: 0.8rem;
            margin: 0.2rem;
            display: inline-block;
        }}
        ol, ul {{ padding-left: 1.5rem; }}
        li {{ margin-bottom: 0.5rem; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div>
                <div class="header-title">[ DFIR ] Memory Forensics & Incident Triage</div>
                <div style="color: var(--text-muted); font-size: 0.9rem;">Volatility 3 Cyber Suite v2.0.0 — Automated Forensic Engine</div>
            </div>
            <div class="score-box">
                <div style="font-size: 0.8rem; color: var(--text-muted);">THREAT SCORE</div>
                <div class="score-val">{self.result.threat_score}/100</div>
                <div style="font-weight: 700;">[ {self.result.risk_level} ]</div>
            </div>
        </header>

        <div class="card">
            <h2>[ 1. EXECUTIVE TRIAGE SUMMARY ]</h2>
            <p>{self.result.ai_summary}</p>
        </div>

        <div class="card">
            <h2>[ 2. CORRELATED ANOMALIES & INJECTIONS ({len(self.result.findings)}) ]</h2>
            <table>
                <thead>
                    <tr>
                        <th>Severity</th>
                        <th>Category</th>
                        <th>Title</th>
                        <th>Evidence Proof</th>
                    </tr>
                </thead>
                <tbody>
                    {findings_rows}
                </tbody>
            </table>
        </div>

        <div class="card">
            <h2>[ 3. MITRE ATT&CK MAPPING ]</h2>
            <div>{mitre_badges}</div>
        </div>

        <div class="card">
            <h2>[ 4. RECOMMENDED DFIR REMEDIATION ]</h2>
            <ol>{remediations_html}</ol>
        </div>
    </div>
</body>
</html>
"""
        Path(output_path).write_text(html_content, encoding="utf-8")
        return html_content
